### ISSUE TITLE
add NATS support 2️⃣: capsule is the client (we call functions through NATS query)

### ISSUE THREAD

**Issue by k33g** [bots-garden/capsule#10]

**Comment by gedw99** [comment]
NATS jetstream support would be awesome. Its the first thing i thought of when i saw capsule.

Some ideas that come to mind

Host functions can then do pipelining, using the NATS KV store to store the data that the wasm function operate on.. As each wasm func runs it can use the NATS KV to set and get data. SO you end up with aggregations.

You can link a change to a dataset in the KV, to kick off new functions, by using the "nats kv watch". So you sort of end up with a excel db, where the functions as in wasm and when a function changes or the data changes everything updates.

The NATS object store is possibly useful for storing the WASM.You can then wrap the registry to look into the NATS object store for it.

The bonux of all this is that you get clustering and gateways for automatica HA, but also security for free on top of all the NATS feature set.

**Comment by gedw99** [comment]
The tunnel  can also use NATS.

https://github.com/codegangsta/caddy-nats shows how easy it is with caddy.

**Comment by k33g** [comment]
👋 @gedw99 
My first plan is to do a lot of 🐛 hunting + code gardening (I did many dirty things with the host functions 😣 ... because I'm learning Go). At the same time, I'm learning NATS (I need to find time).

My first idea is to use a module like an actor (but I need to experiment. I fear having problems with shared memory management)

The NATS KV store looks like a very promising idea 🙂👍

**Comment by gedw99** [comment]
here is a link to the shared objects: https://docs.nats.io/nats-concepts/jetstream/obj_store/obj_walkthrough

And a link to the KV: https://docs.nats.io/nats-concepts/jetstream/key-value-store/kv_walkthrough

For setup of clusters and gateways for HA i recommend: https://github.com/ConnectEverything/nats-by-example

Actors is a good idea. I have used this before: https://fossil.wellquite.org/repo/actors/doc/trunk/README.md and https://wellquite.org/posts/lets_build/edist_actors/

**Comment by gedw99** [comment]
The Nats additions look great !! thanks @k33g
