### ISSUE TITLE
NATS: subscribe to several subjects

### ISSUE THREAD

**Issue by k33g** [bots-garden/capsule#135]

**Comment by gedw99** [comment]
https://github.com/memphisdev/memphis-broker
- Abstraction over NATS with Web GUI.
- Helps user to see and build system that use NATS.

**Comment by k33g** [comment]
NATS support has been removed with `v0.3.4 🍋 [lemon]`

A new Capsule application with NATS support will be developed thanks to:
- https://github.com/bots-garden/capsule-host-sdk
- https://github.com/bots-garden/capsule-module-sdk
