### ISSUE TITLE
NATS: use a set of NATS servers

### ISSUE THREAD

**Issue by k33g** [bots-garden/capsule#136]

**Comment by gedw99** [comment]
https://github.com/ConnectEverything/nats-by-example/tree/main/examples/operations/replace-cluster-nodes/shell

**Comment by k33g** [comment]
NATS support has been removed with `v0.3.4 🍋 [lemon]`

A new Capsule application with NATS support will be developed thanks to:
- https://github.com/bots-garden/capsule-host-sdk
- https://github.com/bots-garden/capsule-module-sdk
