### ISSUE TITLE
Load another wasm module from a wasm module (with host function)

### ISSUE THREAD

**Issue by k33g** [bots-garden/capsule#165]
Probably a bad idea

**Comment by gedw99** [comment]
Its not a bad idea. 

When you have a project in goalng that then needs to use cgo to impot a rust or c package, its hellish.  
There is another project trying to do this with Wazero.

But with WASM you can can compile each separately, and then get your golang wasm to call the rust wasm. 

The trick is how this is designed. There are a few ways.

**Comment by k33g** [comment]
I will wait the WASM components
