### ISSUE TITLE
Install in user-defined path

### ISSUE THREAD

**Issue by rcarmo** [bots-garden/capsule#178]
I like this a lot, but I found that the installation path is hardcoded to `/usr/local/bin`, and that the install script uses `sudo`. Now, the plot twist: _I don't even run `brew` under my own user, and my user can't run `sudo`._ I run it in a separate window under another user that has admin privileges, and install all other binaries I use under `$HOME/.local/bin`, so it would be awesome if Capsule already allowed for that.

**Comment by k33g** [comment]
👋 @rcarmo I'm on the move all week, but I will dig into this at the end of the week (and it will improve my Linux skills)

**Comment by k33g** [comment]
@rcarmo https://github.com/bots-garden/capsule/blob/main/install-capsule-launcher.sh
